### ISSUE TITLE
Have example configuration that follows the guides exactly

### ISSUE THREAD

**Issue by riley-martine** [recyclarr/wiki#15]
Thank you for your hard work on this project. Apologies if this is not clear, I have covid right now.

Most of the time I want a starting point to diverge from; that starting point is what the guides say exactly. I don't want to translate each part of the guides into recyclarr syntax. It would be very helpful if there was a prominently placed example config file that shows how to do exactly what the guides say. (Maybe with a couple variations, but they should be all be exactly copy-pastable in full).

 I think this is matching the guides for radarr (for the HD Bluray + WEB format):

```yaml
radarr:
  radarr:
    base_url: http://localhost:7878
    # must create ~/.config/recyclarr/secrets.yaml
    api_key: !secret radarr_api_key
    delete_old_custom_formats: false
    replace_existing_custom_formats: true
    quality_profiles:
      - name: HD Bluray + WEB
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: Bluray-720p
    custom_formats:
      - trash_ids:
          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

          # HQ Release Groups
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03

          # Misc
          - 0d91270a7255a1e388fa85e959f359d8 # FreeLeech
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2


          # Unwanted
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 0a3f082873eb454bde444150b70253cc # Extras
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)

          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - f6ff65b3f4b464a79dcc75950fe20382 # CRAV
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
          - fbca986396c5e695ef7b2def3c755d01 # OViD
        quality_profiles:
          - name: HD Bluray + WEB
```

I am working on translating the sonarr guides. I think I need to have two sonarr instances.

**Comment by riley-martine** [comment]
Ideally, this could all even be collapsed into

```yaml
radarr:
  radarr:
      base_url: http://localhost:7878
      # must create ~/.config/recyclarr/secrets.yaml
      api_key: !secret radarr_api_key
      defaults: true
```
