### ISSUE TITLE
First configuration example does not work out of the box

### ISSUE THREAD

**Issue by JasperJuergensen** [recyclarr/wiki#86]
The [first configuration example on the Configuration Examples](https://recyclarr.dev/wiki/yaml/config-examples/#update-as-much-as-possible-in-both-sonarr-and-radarr-with-a-single-config) page does not work out of the box because instance names need to be unique.

Error when running the config:
```
[ERR] The following instance names are duplicated: ["main"]
[ERR] Instance names are unique and may not be reused
```

**Configuration:**

```yaml
sonarr:
  main:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey
    quality_definition:
      type: series
    custom_formats:
      - trash_ids:
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
        assign_scores_to:
          - name: WEB-1080p

radarr:
  main:
    base_url: !secret radarr_url
    api_key: !secret radarr_apikey
    quality_definition:
      type: movie
      preferred_ratio: 0.5
    custom_formats:
      - trash_ids:
        # HQ Release Groups
        - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
        - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
        - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
        - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
        - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
        - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        assign_scores_to:
          - name: HD
```

A simple fix would be to rename the instances to `sonarr_main` and `radarr_main`.
